import type { Metadata } from "next";
import { AuthProvider } from "@/context/AuthContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";
import React from "react"
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce Admin Dashboard",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
         <ReactQueryProvider>
          <div className="flex min-h-screen">
            <div className="border-r border-gray-300 dark:border-gray-700">
              <Sidebar />
            </div>
            <div className="flex-1 flex flex-col">
              <Header />
              <main>{children}</main>
            </div>
          </div>
        </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
